// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Server.Data;

#nullable disable

namespace Server.Migrations.Training
{
    [DbContext(typeof(TrainingDbContext))]
    [Migration("20260910134254_TrainingBaseline")]
    partial class TrainingBaseline
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Server.Models.Training.AuditLog", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<string>("AccessReason")
                        .HasColumnType("longtext")
                        .HasColumnName("access_reason");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("action");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<ulong?>("EntityId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("entity_type");

                    b.Property<string>("IpAddress")
                        .HasColumnType("longtext")
                        .HasColumnName("ip_address");

                    b.Property<string>("NewValue")
                        .HasColumnType("longtext")
                        .HasColumnName("new_value");

                    b.Property<string>("OldValue")
                        .HasColumnType("longtext")
                        .HasColumnName("old_value");

                    b.Property<string>("UserAgent")
                        .HasColumnType("longtext")
                        .HasColumnName("user_agent");

                    b.Property<ulong?>("UserId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("audit_logs");
                });

            modelBuilder.Entity("Server.Models.Training.ClassRecord", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<string>("AcademicYear")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("academic_year");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<ulong?>("OrganizationalUnitId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("organizational_unit_id");

                    b.Property<string>("Semester")
                        .HasColumnType("longtext")
                        .HasColumnName("semester");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationalUnitId");

                    b.ToTable("classes");
                });

            modelBuilder.Entity("Server.Models.Training.ClassificationLevel", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<int>("LevelOrder")
                        .HasColumnType("int")
                        .HasColumnName("level_order");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("classification_levels");
                });

            modelBuilder.Entity("Server.Models.Training.DownloadLog", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<string>("DenialReason")
                        .HasColumnType("longtext")
                        .HasColumnName("denial_reason");

                    b.Property<DateTime>("DownloadedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("downloaded_at");

                    b.Property<ulong>("FileId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("file_id");

                    b.Property<ulong?>("FileSize")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("file_size");

                    b.Property<string>("IpAddress")
                        .HasColumnType("longtext")
                        .HasColumnName("ip_address");

                    b.Property<ulong?>("LectureId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("lecture_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<string>("UserAgent")
                        .HasColumnType("longtext")
                        .HasColumnName("user_agent");

                    b.Property<ulong>("UserId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("FileId");

                    b.HasIndex("LectureId");

                    b.HasIndex("UserId", "DownloadedAt");

                    b.ToTable("download_logs");
                });

            modelBuilder.Entity("Server.Models.Training.FilePermission", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<string>("AccessReason")
                        .HasColumnType("longtext")
                        .HasColumnName("access_reason");

                    b.Property<bool>("CanDownload")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("can_download");

                    b.Property<bool>("CanPrint")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("can_print");

                    b.Property<bool>("CanView")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("can_view");

                    b.Property<ulong?>("ClassId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("class_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expires_at");

                    b.Property<ulong>("FileId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("file_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<ulong?>("UserId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("FileId");

                    b.HasIndex("UserId");

                    b.ToTable("file_permissions");
                });

            modelBuilder.Entity("Server.Models.Training.FileRecord", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<string>("ChecksumSha256")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("checksum_sha256");

                    b.Property<ulong>("ClassificationLevelId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("classification_level_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Extension")
                        .HasColumnType("longtext")
                        .HasColumnName("extension");

                    b.Property<ulong>("FileSize")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("file_size");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("file_type");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("mime_type");

                    b.Property<string>("OriginalName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("original_name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("storage_path");

                    b.Property<string>("StoredName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("stored_name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<ulong>("UploadedBy")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("uploaded_by");

                    b.HasKey("Id");

                    b.HasIndex("ClassificationLevelId");

                    b.HasIndex("UploadedBy");

                    b.ToTable("files");
                });

            modelBuilder.Entity("Server.Models.Training.FileVersion", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<string>("ChangeNote")
                        .HasColumnType("longtext")
                        .HasColumnName("change_note");

                    b.Property<string>("ChecksumSha256")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("checksum_sha256");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<ulong>("FileId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("file_id");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("storage_path");

                    b.Property<string>("StoredName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("stored_name");

                    b.Property<ulong>("UploadedBy")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("uploaded_by");

                    b.Property<int>("Version")
                        .HasColumnType("int")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("UploadedBy");

                    b.HasIndex("FileId", "Version")
                        .IsUnique();

                    b.ToTable("file_versions");
                });

            modelBuilder.Entity("Server.Models.Training.LearningProgress", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<bool>("Completed")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("completed");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("completed_at");

                    b.Property<string>("CompletedParts")
                        .HasColumnType("longtext")
                        .HasColumnName("completed_parts");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("LastAccessedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_accessed_at");

                    b.Property<ulong>("LectureId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("lecture_id");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext")
                        .HasColumnName("notes");

                    b.Property<decimal>("ProgressPercent")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("progress_percent");

                    b.Property<int?>("QuizScore")
                        .HasColumnType("int")
                        .HasColumnName("quiz_score");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<ulong>("UserId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("LectureId");

                    b.HasIndex("UserId", "LectureId")
                        .IsUnique();

                    b.ToTable("learning_progress");
                });

            modelBuilder.Entity("Server.Models.Training.Lecture", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<DateTime?>("CloseAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("close_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<DateTime?>("PublishAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("publish_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<ulong>("SubjectId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("subject_id");

                    b.Property<ulong>("TeacherId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("teacher_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .HasColumnType("int")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherId");

                    b.ToTable("lectures");
                });

            modelBuilder.Entity("Server.Models.Training.LectureFile", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<DateTime?>("CloseAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("close_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int")
                        .HasColumnName("display_order");

                    b.Property<ulong>("FileId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("file_id");

                    b.Property<bool>("IsDownloadable")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_downloadable");

                    b.Property<bool>("IsPrintable")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_printable");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_visible");

                    b.Property<ulong>("LectureId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("lecture_id");

                    b.Property<DateTime?>("PublishAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("publish_at");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("FileId");

                    b.HasIndex("LectureId", "FileId")
                        .IsUnique();

                    b.ToTable("lecture_files");
                });

            modelBuilder.Entity("Server.Models.Training.LecturePermission", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<bool>("CanView")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("can_view");

                    b.Property<ulong>("ClassId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("class_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expires_at");

                    b.Property<ulong>("LectureId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("lecture_id");

                    b.Property<DateTime?>("PublishAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("publish_at");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("LectureId", "ClassId")
                        .IsUnique();

                    b.ToTable("lecture_permissions");
                });

            modelBuilder.Entity("Server.Models.Training.NotificationRecord", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsRead")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_read");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("message");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("read_at");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .HasColumnType("longtext")
                        .HasColumnName("type");

                    b.Property<ulong>("UserId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("notifications");
                });

            modelBuilder.Entity("Server.Models.Training.OrganizationalUnit", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<ulong?>("ParentId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("parent_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<string>("UnitType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("unit_type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("organizational_units");
                });

            modelBuilder.Entity("Server.Models.Training.Permission", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<string>("Module")
                        .HasColumnType("longtext")
                        .HasColumnName("module");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("permissions");
                });

            modelBuilder.Entity("Server.Models.Training.QuizQuestion", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<int>("CorrectIndex")
                        .HasColumnType("int")
                        .HasColumnName("correct_index");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Explanation")
                        .HasColumnType("longtext")
                        .HasColumnName("explanation");

                    b.Property<ulong>("LectureId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("lecture_id");

                    b.Property<string>("OptionsJson")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("options_json");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int")
                        .HasColumnName("order_index");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("question");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("LectureId");

                    b.ToTable("quiz_questions");
                });

            modelBuilder.Entity("Server.Models.Training.RetentionPolicy", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<int?>("ArchiveAfterDays")
                        .HasColumnType("int")
                        .HasColumnName("archive_after_days");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int?>("DeleteAfterDays")
                        .HasColumnType("int")
                        .HasColumnName("delete_after_days");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("entity_type");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_enabled");

                    b.Property<int>("RetentionDays")
                        .HasColumnType("int")
                        .HasColumnName("retention_days");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("retention_policies");
                });

            modelBuilder.Entity("Server.Models.Training.Role", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("roles");
                });

            modelBuilder.Entity("Server.Models.Training.RolePermission", b =>
                {
                    b.Property<ulong>("RoleId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("role_id");

                    b.Property<ulong>("PermissionId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("permission_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("role_permissions");
                });

            modelBuilder.Entity("Server.Models.Training.SecurityAlert", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<string>("AlertType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("alert_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("resolved_at");

                    b.Property<ulong?>("ResolvedBy")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("resolved_by");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("severity");

                    b.Property<string>("SourceIp")
                        .HasColumnType("longtext")
                        .HasColumnName("source_ip");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<ulong?>("UserId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ResolvedBy");

                    b.HasIndex("UserId");

                    b.ToTable("security_alerts");
                });

            modelBuilder.Entity("Server.Models.Training.StudentClass", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<ulong>("ClassId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("class_id");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("joined_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<ulong>("StudentId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("student_id");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("StudentId", "ClassId")
                        .IsUnique();

                    b.ToTable("student_classes");
                });

            modelBuilder.Entity("Server.Models.Training.Subject", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<decimal?>("Credits")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("credits");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<ulong?>("OrganizationalUnitId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("organizational_unit_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationalUnitId");

                    b.ToTable("subjects");
                });

            modelBuilder.Entity("Server.Models.Training.SystemSetting", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<bool>("IsSensitive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_sensitive");

                    b.Property<string>("SettingKey")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("setting_key");

                    b.Property<string>("SettingType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("setting_type");

                    b.Property<string>("SettingValue")
                        .HasColumnType("longtext")
                        .HasColumnName("setting_value");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<ulong?>("UpdatedBy")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("system_settings");
                });

            modelBuilder.Entity("Server.Models.Training.TeacherSubject", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<ulong>("SubjectId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("subject_id");

                    b.Property<ulong>("TeacherId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("teacher_id");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherId", "SubjectId")
                        .IsUnique();

                    b.ToTable("teacher_subjects");
                });

            modelBuilder.Entity("Server.Models.Training.User", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .HasColumnType("longtext")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsProfileLocked")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_profile_locked");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_login_at");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("must_change_password");

                    b.Property<ulong?>("OrganizationalUnitId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("organizational_unit_id");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .HasColumnType("longtext")
                        .HasColumnName("phone");

                    b.Property<ulong>("RoleId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("role_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<string>("StudentCode")
                        .HasColumnType("longtext")
                        .HasColumnName("student_code");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationalUnitId");

                    b.HasIndex("RoleId");

                    b.ToTable("users");
                });

            modelBuilder.Entity("Server.Models.Training.UserClearanceLevel", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<ulong>("ClassificationLevelId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("classification_level_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expires_at");

                    b.Property<DateTime>("GrantedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("granted_at");

                    b.Property<ulong>("GrantedBy")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("granted_by");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<ulong>("UserId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ClassificationLevelId");

                    b.HasIndex("GrantedBy");

                    b.HasIndex("UserId");

                    b.ToTable("user_clearance_levels");
                });

            modelBuilder.Entity("Server.Models.Training.UserMfa", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("EnabledAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("enabled_at");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_enabled");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("method");

                    b.Property<string>("SecretEncrypted")
                        .HasColumnType("longtext")
                        .HasColumnName("secret_encrypted");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<ulong>("UserId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("user_mfa");
                });

            modelBuilder.Entity("Server.Models.Training.UserSession", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("device_id");

                    b.Property<string>("DeviceName")
                        .HasColumnType("longtext")
                        .HasColumnName("device_name");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expires_at");

                    b.Property<string>("IpAddress")
                        .HasColumnType("longtext")
                        .HasColumnName("ip_address");

                    b.Property<DateTime?>("LastActivityAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_activity_at");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("revoked_at");

                    b.Property<string>("SessionTokenHash")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("session_token_hash");

                    b.Property<string>("UserAgent")
                        .HasColumnType("longtext")
                        .HasColumnName("user_agent");

                    b.Property<ulong>("UserId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("user_sessions");
                });

            modelBuilder.Entity("Server.Models.Training.WatchHistory", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<bool>("Completed")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("completed");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<decimal?>("DurationSeconds")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("duration_seconds");

                    b.Property<ulong>("FileId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("file_id");

                    b.Property<decimal>("LastPositionSeconds")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("last_position_seconds");

                    b.Property<DateTime>("LastWatchedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_watched_at");

                    b.Property<ulong?>("LectureId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("lecture_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<ulong>("UserId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("FileId");

                    b.HasIndex("LectureId");

                    b.HasIndex("UserId", "FileId")
                        .IsUnique();

                    b.ToTable("watch_history");
                });

            modelBuilder.Entity("Server.Models.Training.AuditLog", b =>
                {
                    b.HasOne("Server.Models.Training.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("Server.Models.Training.ClassRecord", b =>
                {
                    b.HasOne("Server.Models.Training.OrganizationalUnit", "OrganizationalUnit")
                        .WithMany("Classes")
                        .HasForeignKey("OrganizationalUnitId");

                    b.Navigation("OrganizationalUnit");
                });

            modelBuilder.Entity("Server.Models.Training.DownloadLog", b =>
                {
                    b.HasOne("Server.Models.Training.FileRecord", "File")
                        .WithMany()
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.Models.Training.Lecture", "Lecture")
                        .WithMany()
                        .HasForeignKey("LectureId");

                    b.HasOne("Server.Models.Training.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("File");

                    b.Navigation("Lecture");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Server.Models.Training.FilePermission", b =>
                {
                    b.HasOne("Server.Models.Training.ClassRecord", "Class")
                        .WithMany()
                        .HasForeignKey("ClassId");

                    b.HasOne("Server.Models.Training.FileRecord", "File")
                        .WithMany("Permissions")
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.Models.Training.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Class");

                    b.Navigation("File");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Server.Models.Training.FileRecord", b =>
                {
                    b.HasOne("Server.Models.Training.ClassificationLevel", "ClassificationLevel")
                        .WithMany()
                        .HasForeignKey("ClassificationLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.Models.Training.User", "Uploader")
                        .WithMany()
                        .HasForeignKey("UploadedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClassificationLevel");

                    b.Navigation("Uploader");
                });

            modelBuilder.Entity("Server.Models.Training.FileVersion", b =>
                {
                    b.HasOne("Server.Models.Training.FileRecord", "File")
                        .WithMany("Versions")
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.Models.Training.User", "Uploader")
                        .WithMany()
                        .HasForeignKey("UploadedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("File");

                    b.Navigation("Uploader");
                });

            modelBuilder.Entity("Server.Models.Training.LearningProgress", b =>
                {
                    b.HasOne("Server.Models.Training.Lecture", "Lecture")
                        .WithMany()
                        .HasForeignKey("LectureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.Models.Training.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lecture");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Server.Models.Training.Lecture", b =>
                {
                    b.HasOne("Server.Models.Training.Subject", "Subject")
                        .WithMany("Lectures")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.Models.Training.User", "Teacher")
                        .WithMany("Lectures")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Server.Models.Training.LectureFile", b =>
                {
                    b.HasOne("Server.Models.Training.FileRecord", "File")
                        .WithMany("LectureFiles")
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.Models.Training.Lecture", "Lecture")
                        .WithMany("LectureFiles")
                        .HasForeignKey("LectureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("File");

                    b.Navigation("Lecture");
                });

            modelBuilder.Entity("Server.Models.Training.LecturePermission", b =>
                {
                    b.HasOne("Server.Models.Training.ClassRecord", "Class")
                        .WithMany("LecturePermissions")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.Models.Training.Lecture", "Lecture")
                        .WithMany("Permissions")
                        .HasForeignKey("LectureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Lecture");
                });

            modelBuilder.Entity("Server.Models.Training.NotificationRecord", b =>
                {
                    b.HasOne("Server.Models.Training.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Server.Models.Training.OrganizationalUnit", b =>
                {
                    b.HasOne("Server.Models.Training.OrganizationalUnit", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Server.Models.Training.QuizQuestion", b =>
                {
                    b.HasOne("Server.Models.Training.Lecture", "Lecture")
                        .WithMany("QuizQuestions")
                        .HasForeignKey("LectureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lecture");
                });

            modelBuilder.Entity("Server.Models.Training.RolePermission", b =>
                {
                    b.HasOne("Server.Models.Training.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.Models.Training.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Server.Models.Training.SecurityAlert", b =>
                {
                    b.HasOne("Server.Models.Training.User", "Resolver")
                        .WithMany()
                        .HasForeignKey("ResolvedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Server.Models.Training.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Resolver");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Server.Models.Training.StudentClass", b =>
                {
                    b.HasOne("Server.Models.Training.ClassRecord", "Class")
                        .WithMany("StudentClasses")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.Models.Training.User", "Student")
                        .WithMany("StudentClasses")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Server.Models.Training.Subject", b =>
                {
                    b.HasOne("Server.Models.Training.OrganizationalUnit", "OrganizationalUnit")
                        .WithMany("Subjects")
                        .HasForeignKey("OrganizationalUnitId");

                    b.Navigation("OrganizationalUnit");
                });

            modelBuilder.Entity("Server.Models.Training.SystemSetting", b =>
                {
                    b.HasOne("Server.Models.Training.User", "Updater")
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Updater");
                });

            modelBuilder.Entity("Server.Models.Training.TeacherSubject", b =>
                {
                    b.HasOne("Server.Models.Training.Subject", "Subject")
                        .WithMany("TeacherSubjects")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.Models.Training.User", "Teacher")
                        .WithMany("TeacherSubjects")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Server.Models.Training.User", b =>
                {
                    b.HasOne("Server.Models.Training.OrganizationalUnit", "OrganizationalUnit")
                        .WithMany("Users")
                        .HasForeignKey("OrganizationalUnitId");

                    b.HasOne("Server.Models.Training.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrganizationalUnit");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Server.Models.Training.UserClearanceLevel", b =>
                {
                    b.HasOne("Server.Models.Training.ClassificationLevel", "ClassificationLevel")
                        .WithMany()
                        .HasForeignKey("ClassificationLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.Models.Training.User", "Granter")
                        .WithMany()
                        .HasForeignKey("GrantedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Server.Models.Training.User", "User")
                        .WithMany("ClearanceLevels")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClassificationLevel");

                    b.Navigation("Granter");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Server.Models.Training.UserMfa", b =>
                {
                    b.HasOne("Server.Models.Training.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Server.Models.Training.UserSession", b =>
                {
                    b.HasOne("Server.Models.Training.User", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Server.Models.Training.WatchHistory", b =>
                {
                    b.HasOne("Server.Models.Training.FileRecord", "File")
                        .WithMany()
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.Models.Training.Lecture", "Lecture")
                        .WithMany()
                        .HasForeignKey("LectureId");

                    b.HasOne("Server.Models.Training.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("File");

                    b.Navigation("Lecture");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Server.Models.Training.ClassRecord", b =>
                {
                    b.Navigation("LecturePermissions");

                    b.Navigation("StudentClasses");
                });

            modelBuilder.Entity("Server.Models.Training.FileRecord", b =>
                {
                    b.Navigation("LectureFiles");

                    b.Navigation("Permissions");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("Server.Models.Training.Lecture", b =>
                {
                    b.Navigation("LectureFiles");

                    b.Navigation("Permissions");

                    b.Navigation("QuizQuestions");
                });

            modelBuilder.Entity("Server.Models.Training.OrganizationalUnit", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Classes");

                    b.Navigation("Subjects");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Server.Models.Training.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("Server.Models.Training.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Server.Models.Training.Subject", b =>
                {
                    b.Navigation("Lectures");

                    b.Navigation("TeacherSubjects");
                });

            modelBuilder.Entity("Server.Models.Training.User", b =>
                {
                    b.Navigation("ClearanceLevels");

                    b.Navigation("Lectures");

                    b.Navigation("Sessions");

                    b.Navigation("StudentClasses");

                    b.Navigation("TeacherSubjects");
                });
#pragma warning restore 612, 618
        }
    }
}
